-- generated by wallust — wallpaper-derived base16 palette for neovim
return {
  base00 = "#010D0C",
  base01 = "#6C7171",
  base02 = "#78A9A1",
  base03 = "#78A9A1",
  base04 = "#95DCD1",
  base05 = "#A9E6DD",
  base06 = "#95DCD1",
  base07 = "#95DCD1",
  base08 = "#38A191",
  base09 = "#39C6B1",
  base0A = "#64958F",
  base0B = "#4BA194",
  base0C = "#627575",
  base0D = "#63977E",
  base0E = "#627A78",
  base0F = "#39C6B1",
}
