# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #A9E6DD
background         #010D0C
cursor             #568D86

active_tab_foreground     #010D0C
active_tab_background     #A9E6DD
inactive_tab_foreground   #A9E6DD
inactive_tab_background   #010D0C

active_border_color   #A9E6DD
inactive_border_color #010D0C
bell_border_color     #068A76

color0      #6C7171
color1		#38A191
color2		#4BA194
color3		#64958F
color4		#63977E
color5		#627A78
color6		#627575
color7		#95DCD1
color8		#78A9A1
color9		#39C6B1
color10		#39B9A5
color11		#559E94
color12		#5CA581
color13		#63827F
color14		#637D7A
color15		#95DCD1
