-- generated by wallust — wallpaper-derived base16 palette for neovim
return {
  base00 = "{{background}}",
  base01 = "{{color0 | lighten(0.20)}}",
  base02 = "{{color8 | lighten(0.20)}}",
  base03 = "{{color8 | lighten(0.20)}}",
  base04 = "{{color7 | lighten(0.20)}}",
  base05 = "{{foreground}}",
  base06 = "{{color7 | lighten(0.20)}}",
  base07 = "{{color15 | lighten(0.20)}}",
  base08 = "{{color1 | lighten(0.20)}}",
  base09 = "{{color9 | lighten(0.20)}}",
  base0A = "{{color3 | lighten(0.20)}}",
  base0B = "{{color2 | lighten(0.20)}}",
  base0C = "{{color6 | lighten(0.20)}}",
  base0D = "{{color4 | lighten(0.20)}}",
  base0E = "{{color5 | lighten(0.20)}}",
  base0F = "{{color9 | lighten(0.20)}}",
}
